name: CI/CD - Podman build & BootC AMI

on:
  push:
    paths:
      - "Containerfile"
      - "index.html"
      - ".github/workflows/ci.yaml"
  workflow_dispatch:

env:
  REGISTRY: quay.io
  IMAGE_NAME: 7910trio/sy-bootc-httpd
  AWS_REGION: ap-northeast-2
  AWS_BUCKET: sy-bootc-import-bucket
  AMI_NAME_PREFIX: sy-bootc-httpd-ami
  AWS_OUTPUT_FORMAT: json

jobs:
  build-and-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----------------------------
      # 필수 도구 설치
      # ----------------------------
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y podman unzip curl jq btrfs-progs

      - name: Install AWS CLI via snap
        run: |
          sudo snap install aws-cli --classic
          aws --version

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region $AWS_REGION
          aws configure set output $AWS_OUTPUT_FORMAT

      # ----------------------------
      # 이미지 태그 설정
      # ----------------------------
      - name: Set image tag (commit-based)
        id: vars
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "TAG=${SHORT_SHA}" >> $GITHUB_ENV
          echo "FULL_IMAGE=${REGISTRY}/${IMAGE_NAME}:${SHORT_SHA}" >> $GITHUB_ENV
          echo "AMI_NAME=${AMI_NAME_PREFIX}-${SHORT_SHA}" >> $GITHUB_ENV

      # ----------------------------
      # Quay.io 로그인 및 이미지 빌드
      # ----------------------------
      - name: Login to Quay.io
        run: |
          podman login $REGISTRY \
            -u "${{ secrets.QUAY_USERNAME }}" \
            -p "${{ secrets.QUAY_PASSWORD }}"

      - name: Build container image
        run: |
          podman build -f ./Containerfile -t "$FULL_IMAGE" .

      - name: Push image (commit-tag)
        run: |
          podman push "$FULL_IMAGE"

      # ----------------------------
      # BootC AMI 생성
      # ----------------------------
      - name: Pull container image locally for BootC
        run: |
          sudo podman pull "$FULL_IMAGE"

      - name: Build AMI using BootC Image Builder
        run: |
          sudo podman pull quay.io/centos-bootc/bootc-image-builder:latest

          sudo podman run \
            --rm \
            -it \
            --privileged \
            --pull=newer \
            --security-opt label=type:unconfined_t \
            -v $HOME/.aws:/root/.aws:ro \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            --env AWS_PROFILE=default \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type ami \
            --aws-ami-name "$AMI_NAME" \
            --aws-bucket "$AWS_BUCKET" \
            --aws-region "$AWS_REGION" \
            --rootfs btrfs \
            "$FULL_IMAGE"
