ARG BASE=quay.io/fedora/fedora-bootc:42

FROM ${BASE}

LABEL containers.bootc=1

# See https://docs.fedoraproject.org/en-US/bootc/home-directories
RUN mkdir -p /var/roothome

# Immutable 을 유지하기 위해, dnf update는 수행 X
RUN dnf install -y \
    @core \
    pciutils dmidecode lshw \
    net-tools ethtool \
    sysstat \
    openssh-server \
    podman \
    git gcc make \
    tree tar unzip jq curl wget rsync \
    bash-completion \
    && dnf clean all \
    && rm -rf /var/cache/libdnf5

RUN systemctl enable sshd
RUN systemctl enable podman
